# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
  run_tests(workspace: "ComplexUIProject3.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "ComplexUIProject3")
end
lane :gitpush do

        git_add
        git_commit(path: "*", message: "Version")
        push_to_git_remote
end
lane :gitpull do
        git_pull


end
lane :takeCheckout do | options |
	if options[:branchName]
		sh("git", "checkout", "-b", options[:branchName])
	else
		UI.user_error!("Send the branch name as: <fastlane takeCheckout branchName:NewBranchName>")
	end
end
end
